app/main/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField, FileRequired
from wtforms import StringField
from wtforms.validators import DataRequired, Regexp


class ImgForm(FlaskForm):
    fileimg = FileField(validators=[
        FileRequired(),
        FileAllowed(['png', 'jpg', 'jpeg', 'gif'])
    ])


class URLForm(FlaskForm):
    txturl = StringField(validators=[
        DataRequired(),
        Regexp(r'(?:http\:|https\:)?\/\/.*\.(?:png|jpg|jpeg|gif)$',
               message="Invalid image url.")
    ])

app/__init__.py
from flask import Flask
from flask_wtf.csrf import CSRFProtect

from config import config
from vision.vgg_based import get_image_search

csrf = CSRFProtect()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    csrf.init_app(app)
    # 注册蓝本
    from .main import main
    app.register_blueprint(main)
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)
# 避免循环导入依赖
from . import views, errors

app/main/views.py
import os

from flask import (current_app, flash, redirect, render_template, request,
                   send_from_directory, url_for)
from werkzeug.utils import secure_filename

from utils import download

from .. import get_image_search
from . import main
from .forms import ImgForm, URLForm

# 不同数据集有不同的路径
dataset_path_dict = {
    'holiday': 'holiday/jpg/',
    'ukbench': 'ukbench/full/',
}


@main.route('/', methods=['GET', 'POST'])
def index():
    imgform = ImgForm()
    urlform = URLForm()

    if imgform.validate_on_submit():
        file = imgform.fileimg.data
        filename = secure_filename(file.filename)
        filepath = os.path.join(current_app.config['UPLOAD_DIR'], filename)
        if not os.path.exists(filepath):
            file.save(filepath)
        return redirect(url_for('.result', filename=filename))
    elif urlform.validate_on_submit():
        url = urlform.txturl.data
        filename = secure_filename(url.split('/')[-1])
        filepath = os.path.join(current_app.config['UPLOAD_DIR'], filename)
        download(url, current_app.config['UPLOAD_DIR'], filename)
        if not os.path.exists(filepath):
            flash('无法取回指定URL的图片')
            return redirect(url_for('.index'))
        else:
            return redirect(url_for('.result', filename=filename))
    return render_template('index.html')


@main.route('/result', methods=['GET'])
def result():
    filename = request.args.get('filename')
    uri = os.path.join(current_app.config['UPLOAD_DIR'], filename)
    img_d, images, scores = get_image_search(uri)
    dataset = 'holiday'
    images = [os.path.join(dataset_path_dict[dataset], i) for i in images]
    print(images)

    return render_template('result.html', filename=filename, images=images)


@main.route('/images/<path:uri>')
def download_file(uri):
    return send_from_directory(current_app.config['DATABASE_DIR'],
                               uri, as_attachment=True)

app/templates/base.html
<!DOCTYPE html>
<html>

<head>
{% block head %}
    <title>{% block title %}{% endblock %}</title>
    {% block styles %}
        <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}" type="image/x-icon">
        <link rel="icon" sizes="any" href="{{ url_for('static', filename='img/favicon.ico') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/base.css') }}">
    {% endblock %}
{% endblock %}
</head>

<body>
{% block body %}
    <div class="wrapper">
        <div class="header">
        {% block header %}
            <a href="/" title="SoTu">
                <img src="{{ url_for('static', filename='img/lo.png') }}" width="50" height="50">
                <span>CNN IMAGE RETRIEVAL</span>
            </a>
        {% endblock %}
        </div>
        <div class="content">
        {% block content %}
        {% endblock %}
        </div>
        <!-- <div class="footer">
        {% block footer %}
        {% endblock %}
        </div> -->
    </div>
    {% block scripts %}
        <script src="{{ url_for('static', filename='js/jquery-3.3.1.js') }}"></script>
        <script src="{{ url_for('static', filename='js/base.js') }}"></script>
    {% endblock %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <script>alert("{{ message|safe }}");</script>
            {% endfor %}
        {% endif %}
    {% endwith %}
{% endblock %}
</body>

</html>

app/templates/csrf_error.html
{% extends "base.html" %}

{% block title %}CNN IMAGE RETRIEVAL SOTU -  ERROR{% endblock %}

{% block content %}
    <h1>{{ reason }}</h1>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}CNN IMAGE RETRIEVAL - SOTU{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/index.css') }}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="forms">
            <form id="imgform" method="POST" enctype="multipart/form-data" name="imgform">
                <label for="fileimg" id="upload">本地上传</label>
                <input type="file" name="fileimg" id="fileimg">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            </form>
            <form id="urlform" method="POST" enctype="musltipart/form-data" name="urlform">
                <input type="text" id="txturl" name="txturl" placeholder="在此处粘贴图片网址" autocomplete="off">
                <input type="button" id="btnsubmit" name="btnsubmit">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            </form>
            <input type="button" id="btnclose" name="btnclose">
        </div>
        <div class="dragtip" id="dragtip">拖放图片到此处试试</div>
        <div class="dropzone" id="dropzone" style="display:none;">
            <span>请拖放图片到此处</span>
            <div class="dropfocus focus_top_left"></div>
            <div class="dropfocus focus_bottom_left"></div>
            <div class="dropfocus focus_top_right"></div>
            <div class="dropfocus focus_bottom_right"></div>
        </div>
        <div class="uploadtip" id="uploadtip" style="display:none;">
            <img src="{{ url_for('static', filename='img/uploading.gif') }}">
            <span>正在识别中，请稍候...</span>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/index.js') }}"></script>
{% endblock %}

app/templates/result.html
{% extends "base.html" %}

{% block title %}CNN IMAGE RETRIEVAL SOTU{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/result.css') }}">
{% endblock %}

{% block content %}
    <div class="image-wrapper">
        <div class="image-target">
            <img src="{{ url_for('static', filename='uploads/') }}{{ filename }}">
            <div class="image-info">目标图片</div>
        </div>
    {% if images %}
        <div class="image-tip">
            <span>结果图片 | 按相似度排序</span>
        </div>
        <div class="image-grid">
        {% for image in images %}
            <div class="image-item">
                <img src="{{ url_for('main.download_file', uri=image) }}">
                <div class="image-overlay"></div>
            </div>
        {% endfor %}
        </div>
    {% else %}
        <h1>没有类似图片</h1>
    {% endif %}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/result.js') }}"></script>
{% endblock %}